
[general]
	announce_new_song = 0
	link_mode = 1
	first_time = false
	mod_mode = -1
	notification_album_art_location = 1
	music_service = "spotify"
	announcement_message = "&aCraftify > &7Now Playing: &b${song} by ${artists}"

[servers]
	allowed_servers = ""
	send_songs_to_servers = false

[rendering]
	controls = false
	display_mode = 2
	position_x_offset = 0.0
	position_y_offset = 0.0
	anchor_point = 0
	render_type = 2

[login]
	refresh_token = "AQAC4VHQ2FuyxqVkwkY2OOrkx-Go5mVWuaJ-KocPc5BxT9487ThEFG1NICeMjsiz0N65D7QZyQtkLJ4MGhTqO-CBbMYMYI2-SrnRVc3qQ8LfMJUYqI-HtLDCckZABtZ5sLg"
	spotify_login_token = "BQBGdSVjDEefg1_YrYHjuE_V-zuLogDQIoLViXs-Htm2iW4snt-VaS-fmlauWdQYfsLunUKtyzf79rRkqcGa-O5_mo6Mns3R6QJ_p3iBVcT75oc7V7g74JN6jlAKS-EJH7nefg7hze20ACgD3hl5qks8uRu6d6BgerZ-FdYl_6UQtiqos8PcOduwO8cEMOzhCeZRRIspx4zzeL-1rbAM"
	ytmd_token = ""
	service_port = 8880

